apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-500
spec:
  storageClassName: host-pv
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/my-pv/data/pv1"
