apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-1g
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/my-pv/data/pv2"
